# データの可視化

In [1]:
import os

import hvplot
import polars as pl

## 定数定義

In [2]:
DATA_PAR_PATH = os.path.join('..','..','data')
INPUT_PARQUETS_PATH_TAXI = os.path.join(DATA_PAR_PATH,'TAXI','*.parquet')

## データの読み込み

In [3]:
taxis = pl.read_parquet(INPUT_PARQUETS_PATH_TAXI)
taxis

shape: (39_656_098, 19)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ tpep_pick ┆ tpep_drop ┆ passenger ┆ … ┆ improveme ┆ total_amo ┆ congestio ┆ airport_f │
│ ---      ┆ up_dateti ┆ off_datet ┆ _count    ┆   ┆ nt_surcha ┆ unt       ┆ n_surchar ┆ ee        │
│ i64      ┆ me        ┆ ime       ┆ ---       ┆   ┆ rge       ┆ ---       ┆ ge        ┆ ---       │
│          ┆ ---       ┆ ---       ┆ f64       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ f64       │
│          ┆ datetime[ ┆ datetime[ ┆           ┆   ┆ f64       ┆           ┆ f64       ┆           │
│          ┆ ns]       ┆ ns]       ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1        ┆ 2022-01-0 ┆ 2022-01-0 ┆ 2.0       ┆ … ┆ 0.3       ┆ 21.95     ┆ 2.5       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:35:40  ┆ 00:53:29  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2022-01-0 ┆ 2022-01-0 ┆ 1.0       ┆ … ┆ 0.3       ┆ 13.3      ┆ 0.0       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:33:43  ┆ 00:42:07  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2022-01-0 ┆ 2022-01-0 ┆ 1.0       ┆ … ┆ 0.3       ┆ 10.56     ┆ 0.0       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:53:21  ┆ 01:02:19  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2022-01-0 ┆ 2022-01-0 ┆ 1.0       ┆ … ┆ 0.3       ┆ 11.8      ┆ 2.5       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:25:21  ┆ 00:35:23  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2022-01-0 ┆ 2022-01-0 ┆ 1.0       ┆ … ┆ 0.3       ┆ 30.3      ┆ 2.5       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:36:48  ┆ 01:14:20  ┆           ┆   ┆           ┆           ┆           ┆           │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2        ┆ 2022-12-3 ┆ 2023-01-0 ┆ null      ┆ … ┆ 1.0       ┆ 49.26     ┆ null      ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 23:46:00  ┆ 00:11:00  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2022-12-3 ┆ 2022-12-3 ┆ null      ┆ … ┆ 1.0       ┆ 30.23     ┆ null      ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 23:13:24  ┆ 23:29:08  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2022-12-3 ┆ 2022-12-3 ┆ null      ┆ … ┆ 1.0       ┆ 59.08     ┆ null      ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 23:00:49  ┆ 23:26:57  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2022-12-3 ┆ 2022-12-3 ┆ null      ┆ … ┆ 1.0       ┆ 16.74     ┆ null      ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 23:02:50  ┆ 23:16:05  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2022-12-3 ┆ 2022-12-3 ┆ null      ┆ … ┆ 1.0       ┆ 25.1      ┆ null      ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 23:00:15  ┆ 23:22:56  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [4]:
taxis.filter(
    (pl.col('VendorID') == 5)
)

shape: (143, 19)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ tpep_pick ┆ tpep_drop ┆ passenger ┆ … ┆ improveme ┆ total_amo ┆ congestio ┆ airport_f │
│ ---      ┆ up_dateti ┆ off_datet ┆ _count    ┆   ┆ nt_surcha ┆ unt       ┆ n_surchar ┆ ee        │
│ i64      ┆ me        ┆ ime       ┆ ---       ┆   ┆ rge       ┆ ---       ┆ ge        ┆ ---       │
│          ┆ ---       ┆ ---       ┆ f64       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ f64       │
│          ┆ datetime[ ┆ datetime[ ┆           ┆   ┆ f64       ┆           ┆ f64       ┆           │
│          ┆ ns]       ┆ ns]       ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 5        ┆ 2022-01-0 ┆ 2022-01-0 ┆ null      ┆ … ┆ 0.3       ┆ 110.83    ┆ null      ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 14:09:52  ┆ 14:49:26  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 5        ┆ 2022-01-0 ┆ 2022-01-0 ┆ null      ┆ … ┆ 0.3       ┆ 65.22     ┆ null      ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 15:54:31  ┆ 16:43:56  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 5        ┆ 2022-01-0 ┆ 2022-01-0 ┆ null      ┆ … ┆ 0.3       ┆ 33.45     ┆ null      ┆ null      │
│          ┆ 3         ┆ 3         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 16:05:45  ┆ 16:28:00  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 5        ┆ 2022-01-0 ┆ 2022-01-0 ┆ null      ┆ … ┆ 0.3       ┆ 59.1      ┆ null      ┆ null      │
│          ┆ 8         ┆ 8         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 14:36:42  ┆ 15:07:50  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 5        ┆ 2022-01-0 ┆ 2022-01-0 ┆ null      ┆ … ┆ 0.3       ┆ 59.1      ┆ null      ┆ null      │
│          ┆ 9         ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 10:46:22  ┆ 11:10:49  ┆           ┆   ┆           ┆           ┆           ┆           │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 5        ┆ 2022-08-2 ┆ 2022-08-2 ┆ null      ┆ … ┆ 0.3       ┆ 82.48     ┆ null      ┆ null      │
│          ┆ 6         ┆ 6         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 13:57:28  ┆ 15:00:09  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 5        ┆ 2022-08-2 ┆ 2022-08-2 ┆ null      ┆ … ┆ 0.3       ┆ 93.72     ┆ null      ┆ null      │
│          ┆ 6         ┆ 7         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 23:15:27  ┆ 00:02:30  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 5        ┆ 2022-08-3 ┆ 2022-08-3 ┆ null      ┆ … ┆ 0.3       ┆ 75.86     ┆ null      ┆ null      │
│          ┆ 0         ┆ 0         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 07:00:09  ┆ 07:47:31  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 5        ┆ 2022-08-3 ┆ 2022-08-3 ┆ null      ┆ … ┆ 0.3       ┆ 38.12     ┆ null      ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 07:02:39  ┆ 07:21:04  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 5        ┆ 2022-09-1 ┆ 2022-09-1 ┆ null      ┆ … ┆ 0.3       ┆ 150.61    ┆ null      ┆ null      │
│          ┆ 2         ┆ 2         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 17:27:35  ┆ 18:54:56  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [5]:
taxis_ = (
    taxis
    .filter(pl.col('VendorID') == 5)
    .select(
        pl.col('trip_distance'),
        abs(pl.col('tpep_dropoff_datetime') - pl.col('tpep_pickup_datetime')).cast(pl.Float32).alias('duration'),
        pl.col('tip_amount')
    )
)

taxis_

shape: (143, 3)
┌───────────────┬───────────┬────────────┐
│ trip_distance ┆ duration  ┆ tip_amount │
│ ---           ┆ ---       ┆ ---        │
│ f64           ┆ f32       ┆ f64        │
╞═══════════════╪═══════════╪════════════╡
│ 14.58         ┆ 2.3740e12 ┆ 14.04      │
│ 18.26         ┆ 2.9650e12 ┆ 0.0        │
│ 7.08          ┆ 1.3350e12 ┆ 4.21       │
│ 17.2          ┆ 1.8680e12 ┆ 0.0        │
│ 16.99         ┆ 1.4670e12 ┆ 0.0        │
│ …             ┆ …         ┆ …          │
│ 16.67         ┆ 3.7610e12 ┆ 0.0        │
│ 18.2          ┆ 2.8230e12 ┆ 0.0        │
│ 18.43         ┆ 2.8420e12 ┆ 12.11      │
│ 4.34          ┆ 1.1050e12 ┆ 0.0        │
│ 38.59         ┆ 5.2410e12 ┆ 1.43       │
└───────────────┴───────────┴────────────┘

In [6]:
taxis_.plot.scatter(x='trip_distance', y='duration', color='tip_amount')

alt.Chart(...)